version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - confluence
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - .data/confluence-home:/var/atlassian/application-data/confluence
    volumes_from:
      - confluence:ro
  confluence:
    build: ./confluence
    ports:
      - '8090:8090'
