version: '2'
services:
  nginx:
    build: ./nginx
    links:
      - confluence
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  confluence:
    build:
      context: ./confluence
      args:
        CONFLUENCE_HOSTNAME: 'confluence.local'
        TIMEZONE: 'Asia/Tokyo'
    environment:
      CONFLUENCE_CATALINA_MEM: 2048
    extra_hosts:
      - 'confluence.local:127.0.0.1'
    ports:
      - '8090:8090'
    volumes:
      - ./data/confluence-home:/var/atlassian/application-data/confluence
