version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    volumes_from:
      - confluence:ro
  # nginx:
    # build: ./nginx
    # links:
      # - confluence
    # ports:
      # - '80:80'
    # volumes:
      # - /var/run/docker.sock:/tmp/docker.sock:ro
    # volumes_from:
      # - confluence:ro
  confluence:
    build: ./confluence
    environment:
      - VIRTUAL_HOST=confluence.local
      - VIRTUAL_PORT=8090
    links:
      - postgres
    ports:
      - '8090:8090'
    volumes:
      - ./data/confluence-home:/var/atlassian/application-data/confluence
  postgres:
    build: ./postgres
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
